version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: garage-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: garage_webhook
    ports:
      - "3306:3306"
    restart: always

  api:
      build: .
      container_name: garage-api
      network_mode: "host"
      restart: on-failure
      depends_on:
        - mysql
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/garage_webhook?createDatabaseIfNotExist=true&serverTimezone=UTC
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=admin