spring.datasource.url=jdbc:mysql://localhost:3306/garage_webhook?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

server.port=3003

spring.jackson.property-naming-strategy=SNAKE_CASE

server.error.include-stacktrace=never